security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
  providers:
    in_memory_users:
      memory:
        users:
          - identifier: '%env(HTTP_BASIC_AUTH_USERNAME)%'
            password: '%env(HTTP_BASIC_AUTH_PASSWORD)%'
            roles: [ ROLE_USER ]
  firewalls:
    main:
      pattern: ^/
      http_basic: ~
  access_control:
    - { path: ^/product, roles: [ ROLE_USER ], methods: POST}
    - { path: ^/product/*, roles: [ ROLE_USER ],methods: [PUT, DELETE]}